name: Format Check

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/format-check.yml
      - src/**
      - tests/**

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format 18
        run: sudo apt-get install clang-format-18

      - name: Update clang-format to version 18
        run: sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-18 100

      - name: Display clang-format version
        run: clang-format --version

      - name: Run clang-format check
        run: clang-format ./src/*.cc -n --Werror
