name: Format Check

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/format-check.yml
      - src/**
      - tests/**

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add LLVM repo
        run: |
          sudo apt-get update
          sudo apt-get install -y wget lsb-release software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18

      - name: Install clang-format 18
        run: sudo apt-get install -y clang-format-18

      # - name: Uninstall default clang-format
      #   run: sudo apt-get remove -y clang-format

      # - name: Install clang-format
      #   run: sudo apt-get install clang-format

      - name: Display clang-format version
        run: clang-format --version

      - name: Run clang-format check
        run: clang-format ./src/*.cc -n --Werror
