name: Format Check

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/format-check.yml
      - src/**
      - tests/**

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install clang-format-17

      - name: Display clang-format version
        run: clang-format --version

      - name: Run clang-format check
        run: clang-format ./src/*.cc -n --Werror
