name: Format Check

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/format-check.yml
      - src/**
      - tests/**

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Apt update
        run: sudo apt update

      - name: Base install
        run: sudo apt install lsb-release wget software-properties-common gnupg

      - name: Install llvm
        run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

      - name: Install clang-format
        run: sudo apt-get install clang-18
        # run: sudo apt-get install clang-format

      - name: Display clang-format version
        run: clang-format --version

      - name: Run clang-format check
        run: clang-format ./src/*.cc -n --Werror
